baseurl = "https://drpaneas.com"
title = "drpaneas"
languageCode = "en-us"
theme = "terminal-workspace"
paginate = 18

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

[markup]
  [markup.highlight]
    noClasses = false

[permalinks]
  post = "/blog/:year/:month/:day/:title/"

[params]
  author = "Panos Georgiadis"
  description = "Not all those who wander are lost"

  [params.terminal_workspace]
    identity_ascii = """
 ____  ____  ____   __   __ _  ____   __   ____
(    \\(  _ \\(  _ \\ / _\\ (  ( \\(  __) / _\\ / ___)
 ) D ( )   / ) __//    \\/    / ) _) /    \\\\___ \\
(____/(__\\_)(__)  \\_/\\_/\\_)__)(____)\\_/\\_/(____/
"""
    identity_title = "Hi I'm Panos -> drpaneas"
    identity_subtitle = "Born in Greece - living in Germany."
    identity_interests = "💻 automation 🚀 devops ☸ kubernetes 🐧 linux 🕹️ emulation 🧐 QA 🖥 SRE 🦊 hacking 🧑‍🚀 astrophysics"
    quote_heading = "quotes / go by"
    quote_tagline = "Hack the Planet"
    quote_text = "All that is gold does not glitter, Not all those who wander are lost"
    home_post_limit = 5
    all_posts_label = "more posts ->"
    all_tags_label = "all tags ->"
