baseurl = "https://panosgeorgiadis.com/"
title = "drpaneas"
languageCode = "en-us"
theme = "m10c"
paginate = 8

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

[params]
  author = "Panos Georgiadis"
  description = "Open Source developer."
  avatar = "https://www.gravatar.com/avatar/a98d3abef556df10b9dfd4710e368f0e?s=200"
  menu_item_separator = " - "
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/drpaneas"
  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/PanosGeorgiadis"
  [[params.social]]
    icon = "linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/panosgeorgiadis/"

[author]
    name = "Panos Georgiadis"

[permalinks]
    # Optional. Change the permalink format for the 'post' content type.
    # The format shown here is the same one Jekyll/Octopress uses by default.
    post = "/blog/:year/:month/:day/:title/"

  # Default theme
[params.style]
    darkestColor = "#242930"    # left bar
    darkColor = "#353353"       # right background
    lightColor = "#e2dada"      # normal text
    lightestColor = "#fdba31"   # headings
    primaryColor = "#f72585"    # links fdba31
    codeColor = "#35d475"
    avatarColor = "#242930"
    titleColor = "#efcb68"
    headerColor = "#fdba31"
    h1Color = "#e2dada"
    