baseurl = "http://drpaneas.github.io/public/"
title = "Panos Blog"
languageCode = "en"
#disqusShortname = "panosblog"
#disqusShortname = "PanosGeorgiadis"
MetaDataFormat = "toml"
paginate = 10
theme = "hyde-x"

markup = "rst"

[author]
    name = "Panos Georgiadis"

[permalinks]
    # Optional. Change the permalink format for the 'post' content type.
    # The format shown here is the same one Jekyll/Octopress uses by default.
    post = "/blog/:year/:month/:day/:title/"

[indexes]
    # Optional. Use if you want tags and lists.
    category = "categories"

#
# All parameters below here are optional and can be mixed and matched.
#
[params]
    # Used when a given page doesn't set its own.
    defaultDescription = "A personal blog about Linux and stuff"
    defaultKeywords = "panos georgiadis, panos, drpaneas, linux, programming, guitar, paok, opensuse, suse"

    # Changes sidebar background and link/accent colours.
    # See below for more colour options.
    # This also works: "theme-base-08 layout-reverse", or just "layout-reverse".
    theme = "theme-base-08"

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "arta"
   # highlight = "monokai_sublime"

    # Displays under the author name in the sidebar, keep it short.
    # tagline = "~~~~~~~~~~~~~~~~~~~"

    # Metadata used to drive integrations.
    #googleAuthorship = "PanosGeorgiadis"
    #googleAnalytics = "UA-60257842-1"
    #gravatarHash = "a98d3abef556df10b9dfd4710e368f0e"

    # Sidebar social links, avoid enabling too many of these if possible.
    # These should be full URLs.
    #github = "https://github.com/drpaneas/"
    #linkedin = "https://gr.linkedin.com/in/panosgeorgiadis/"
    #googleplus = "https://plus.google.com/+PanosGeorgiadis/posts"
    #facebook = "https://www.facebook.com/paneas"
    #twitter = "https://twitter.com/PanosGeorgiadis"
